# Generated by Django 2.2.4 on 2019-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('tweets', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('img', models.CharField(max_length=255)),
                ('analysis_positive', models.IntegerField()),
                ('analysis_negative', models.IntegerField()),
                ('analysis_neutral', models.IntegerField()),
                ('acceptance_post', models.IntegerField()),
                ('acceptance_neutral', models.IntegerField()),
                ('acceptance_negative', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
