# Generated by Django 2.2.4 on 2019-08-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='report',
            name='img',
            field=models.TextField(default='https://pbs.twimg.com/profile_images/661318201473544192/QYYw4uBv.png'),
        ),
    ]
