# Generated by Django 2.2.4 on 2019-08-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear_api', '0002_auto_20190816_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.TextField(default='https://twitter.com/home'),
        ),
    ]
