# Generated by Django 2.2.4 on 2019-08-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bear_api', '0003_report_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='acceptance_post',
            new_name='acceptance_positive',
        ),
    ]
